config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/jobs'
  use_doorkeeper

  get 'dashboard', to: 'dashboard#index'
  resources :search, only: %i[new show create] do
    post :upload, on: :collection
  end
  resources :keywords, only: %i[index show] do
    get :result, on: :member
  end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  draw :api
end

app/models/search.rb
# frozen_string_literal: true

class Search < ApplicationRecord
  has_many :search_keywords, dependent: :destroy
  has_many :keywords, through: :search_keywords

  belongs_to :user
end

app/controllers/api/v1/search_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class SearchController < ApiController
      before_action :check_file, only: [:upload]

      def upload
        keywords = CsvService.call(File.read(file))
        return too_many_keywords if keywords.count > 100

        search = Search.new(user_id: params[:user_id])
        search.save
        CreateKeywordsAndResultsService.call(search.id, keywords)
        render json: { success: true, search: search, message: 'Keywords are starting to import.' }, status: :created
      end

      def show
        @search = Search.find_by(id: params[:id], user_id: current_user)
        if @search
          @pagy, @keywords = pagy(@search.keywords
                                         .includes(:result))
          render 'show'
        else
          render json: { success: false,
                         error: 'The search you are looking for does not exist. Plese try Search again' }
        end
      end

      private

      def too_many_keywords
        render json: { success: false, error: 'more than 100 keywords' }, status: :unprocessable_entity
      end

      def valid_file?
        file.content_type == 'text/csv' || file.content_type == 'csv'
      end

      def file
        search_params[:file]
      end

      def check_file
        return invalid_file unless file.present? && valid_file?
      end

      def invalid_file
        render json: { success: false, error: 'No file presented' }, status: :unprocessable_entity
      end

      def search_params
        params.require(:search).permit :file, :content_type
      end
    end
  end
end

app/controllers/search_controller.rb
# frozen_string_literal: true

class SearchController < ApplicationController
  before_action :authenticate_user!

  def new
    @search = Search.new
  end

  def upload
    return redirect_to new_search_path, error: 'invalid file' unless valid_file?

    @keywords = CsvService.call(File.read(file))
    return redirect_to new_search_path, error: 'more than 100 keywords' if too_many_keywords?

    @search = Search.new
    render turbo_stream: turbo_stream.replace('keywords', partial: 'temp_keywords', locals: { keywords: @keywords })
  end

  def create
    @search = Search.new(user_id: current_user.id)
    if @search.save
      CreateKeywordsAndResultsService.call(@search.id, keywords)
      redirect_to search_path(@search.id)
    else
      render 'new'
    end
  end

  def show
    @search = Search.find_by(id: params[:id])
    @keywords = @search.keywords.includes(:result)
  end

  private

  def keywords
    search_params[:keywords].split(',')
  end

  def too_many_keywords?
    @keywords.length > 100
  end

  def valid_file?
    file.content_type == 'text/csv' || file.content_type == 'csv'
  end

  def file
    search_params[:csv_file]
  end

  def search_params
    params.require(:search).permit(:csv_file, :keywords)
  end
end

app/views/search/_temp_keywords.html.haml
#keywords
  .card
    .card-body
      .card-title
        .row.p-3
          .col-7
            %h3 Keywords from file
          .col-auto
            = simple_form_for @search, url: search_index_path, method: :post do |f|
              = f.input :keywords, as: :hidden, input_html: { value: keywords.join(',') }
              = f.submit value: 'Import', class: 'btn btn-lg btn-primary'
      .row
        - keywords.each do |keyword|
          .col-md-6
            %li= keyword
    .card-footer
      Total Keywords: #{keywords.count}

app/views/search/new.html.haml
.row.d-flex.justify-content-center.py-5
  .col-md-6
    .card.mb-3
      .card-body
        .card-title.mb-3
          .row.justify-content-between
            .col-auto
              Upload CSV File
            .col-auto
              = link_to 'Download template', asset_path('/templates/template.csv'), download: true
        = simple_form_for @search, url: upload_search_index_path do |f|
          .row
            .col-9.mb-3
              = f.input :csv_file,
                        as: :file,
                        label: false,
                        required: true,
                        input_html: { class: 'btn btn-lg border', accept: '.csv' }
            .col
              = f.submit value: 'Upload', class: 'btn btn-light border btn-lg'

    = turbo_frame_tag "keywords"

app/views/search/show.html.haml
:ruby
  total_keywords = @search.keywords
  saved_keywords = @keywords
  fail_to_save_keywords = total_keywords.count - saved_keywords.count
.row.d-flex.justify-content-center.py-5
  .col-12.col-md-8
    .card.mb-3
      .card-body
        .card-title.mb-3
          .row.d-flex.justify-content-center
            .col-auto.border-end.d-flex.align-items-center
              %h3 Import Summary
            .col-6
              %table.table
                %thead.text-center
                  %th Total
                  %th.text-primary Saved
                  %th.text-danger Failed
                %tbody
                  %tr.text-center
                    %td= total_keywords.count
                    %td= saved_keywords.count
                    %td= fail_to_save_keywords
    .card.mb-3
      .card-body
        .card-title.mb-3
          .row.d-flex.justify-content-between.align-items-center
            .col-auto
              .fs--5.text-secondary Here's your successfully saved keywords
            .col-auto
              %h5.text-secondary Total
              .ms-3=  @keywords.count
        %table.table.text-center
          %caption List of Keywords
          %thead
            %tr
              %th{ scope: 'col' } #
              %th{ scope: 'col' } Keyword
              %th{ scope: 'col' } Actions
          %tbody
            - @keywords.each_with_index do |keyword, index|
              %tr
                %th{ scope: 'row' } #{index +1}.
                %td{ scope: 'row' }= keyword.name
                %td{ scope: 'row' }
                  - if keyword.result
                    = link_to 'Show Result', result_keyword_path(keyword.id)
                  - else
                    = link_to 'Pending', '#'