config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/jobs'
  use_doorkeeper

  get 'dashboard', to: 'dashboard#index'
  resources :search, only: %i[new show create] do
    post :upload, on: :collection
  end
  resources :keywords, only: %i[index show] do
    get :result, on: :member
  end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  draw :api
end

app/models/keyword.rb
# frozen_string_literal: true

class Keyword < ApplicationRecord
  validates :name, presence: true

  belongs_to :user
  has_many :search_keywords, dependent: :destroy
  has_many :searches, through: :search_keywords

  has_one :result, dependent: :destroy
end

app/controllers/api/v1/keywords_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class KeywordsController < ApiController
      def index
        @pagy, @keywords = pagy(current_user.keywords
                                            .includes(:users)
                                            .includes(:searches))
      end
    end
  end
end

app/controllers/keywords_controller.rb
# frozen_string_literal: true

class KeywordsController < ApplicationController
  include Pagy::Backend
  before_action :authenticate_user!

  def index
    @q = current_user.keywords.ransack(params[:q])
    @pagy, @keywords = pagy(@q.result
                              .joins(:result)
                              .order('keywords.created_at desc')
                              .includes(:result), items: 20)
  end

  def result
    keyword = Keyword.find_by id: params[:id]
    @result = keyword.result
  end

  private

  def keyword_params
    params.require(:keyword).permit(:name)
  end
end

app/views/keywords/_keyword.html.haml
.col-md-6.mb-3
  = keyword.name

app/views/keywords/_search_form.html.haml
= simple_form_for :q, method: :get, wrapper: :inline_form do |f|
  .row
    .col-md-3.mb-3
      = f.input :name_cont, label: 'Enter Keyword'
    .col-md-3.mb-3
      .row
        .col-10
          = f.input :created_at_gteq,
                    label: 'From',
                    as: 'date',
                    html5: true
    .col-md-3.mb-3
      .row
        .col-10
          = f.input :created_at_lteq,
                    label: 'To',
                    as: 'date',
                    html5: true
    .col-md-3.d-flex.align-items-center
      = f.button :submit, 'Search', class: 'btn btn-primary me-3'
      = link_to 'Clear', keywords_path, class: 'btn btn-secondary'

app/views/keywords/create.html.haml
%h1 Keywords#create
%p Find me in app/views/keywords/create.html.haml

app/views/keywords/index.html.haml
.row.d-flex.justify-content-center
  .col-10
    .row.justify-content-center
      .col-md-2.border-end.d-flex.align-items-center
        %p.fs-3 Results
      .col-md-10
        = render 'search_form'
%hr
.row.d-flex.justify-content-center
  .col-10
    %table.table.text-center
      %caption List of Keywords
      %thead
        %tr
          %th{ scope: 'col' } #
          %th{ scope: 'col' }
            = sort_link(@q, :name, "Keyword", default_order: :desc)
          %th{ scope: 'col' }
            = sort_link(@q, :result_total_advertisers, "Total Advertisers", default_order: :desc)
          %th{ scope: 'col' }
            = sort_link(@q, :result_total_urls, "Total Urls", default_order: :desc)
          %th{ scope: 'col' } Stats
          %th{ scope: 'col' }
            = sort_link(@q, :created_at, "Created At", default_order: :desc)
      %tbody
        - @keywords.each_with_index do |keyword, index|
          %tr
            %th{ scope: 'row' }= keyword.id
            %td{ scope: 'row' }= keyword.name
            %td{ scope: 'row' }= keyword.result.total_advertisers
            %td{ scope: 'row' }= keyword.result.total_urls
            %td{ scope: 'row' }= keyword.result.stats
            %td{ scope: 'row' }
              = keyword.created_at.strftime('%Y-%m-%d')
            %td{ scope: 'row' }
              - if keyword.result
                = link_to 'Show Details', result_keyword_path(keyword.id)
              - else
                = link_to 'Pending', '#'
        != pagy_bootstrap_nav(@pagy)

app/views/keywords/result.html.haml
:ruby
  nokogiri = Nokogiri::HTML(File.open(ActiveStorage::Blob.service.path_for(@result.html_file.key)))
  urls = nokogiri.search('a').map{|i| i[:href]}
  filtered_urls = urls.grep(/^https\:\/\/(?!.*(google|search\?)).*$/)
.row.d-flex.justify-content-between.mb-3
  .col-auto
    .fs-6
      Result for Keyword:
      %span.fs-2.text-primary #{@result.keyword.name}
  .col-auto
    .fs-6
      Last Crawl At:
      %span.fs-4.text-primary= time_ago_in_words(@result.updated_at)
.row.mb-3.d-flex.justify-content-center
  .col-md-4.align-items-stretch
    .card.mb-3
      .card-body
        .card-title Column Chart
        = column_chart ({ 'Total Urls': @result.total_urls,
                          'Total Advertisers': @result.total_advertisers })

    %ul.list-group.mb-3
      %li.list-group-item
        .fs-6.text-secondary
          Stats:
          %span.fs-5.text-primary #{@result.stats}
      %li.list-group-item
        .fs-6.text-secondary
          Total Urls:
          %span.fs-5.text-primary #{@result.total_urls}
      %li.list-group-item
        .fs-6.text-secondary
          Total Advertisers:
          %span.fs-5.text-primary #{@result.total_advertisers}
      %li.list-group-item
        %span.text-secondary HTML Body:
        = link_to 'Download Here' ,rails_blob_path(@result.html_file, disposition: :attachment)
  .col-md-5.align-items-stretch
    .card
      .card-body
        .card-title Non Google Urls
        %ul
          - filtered_urls.each do |url|
            %li
              =link_to url, url, target: '_blank', class: 'text-decoration-none text-reset'